logging:
  level:
    root: error
  file:
    name: "data/debug.log"
telegram:
  bot:
    username: Tikhoretsk_lawyers_bureau_1_bot
    token: 8100533704:AAHjy7lEuVJbloLq1-nsJQT9q-_PYPeLVZI
    notify:
      delay:
        value: 10
        unit: MINUTES


