logging:
  level:
    root: info
  file:
    name: "data/debug.log"



telegram:
  bot:
    username:
    token:




    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

