logging:
  level:
    root: error
  file:
    name: "data/debug.log"
telegram:
  bot:
    username: Tikhoretsk_lawyers_bureau_1_bot
    token: S{token}
    notify:
      delay:
        value: 10
        unit: MINUTES


